"""Diff the FFmpeg component set of the app against the ffmpeg-core unit.

The app's own FFmpeg was configured by whoever built nPlayer; nothing records
those options. The core unit is built with every native component enabled, so
the question `make deps` cannot answer by itself is whether that set still
covers the app's build. This compares the component names themselves: the
`AVCodec`/`AVInputFormat`/... name literals the app's main binary carries
against the ones the built dylib carries.

The direction that matters is "the app has it, the unit does not": that name is
a container, codec, protocol or bitstream filter which would keep running the
app's 4.4.5. The other direction is capability the unit adds, and is listed so
the difference is explained rather than assumed.

Parsers carry no name (they are keyed by codec id), so they cannot be compared
this way; they are reached through their codec's parser ids.

Usage:
    uv run python dev/tools/enable_set_diff.py
    uv run python dev/tools/enable_set_diff.py --app my.ipa --unit build/LibFFmpegCoreBridge.dylib
"""

from __future__ import annotations

import argparse
import plistlib
import re
import sys
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

# A component definition: `AVCodec ff_foo_decoder = {`, `URLProtocol ff_bar_protocol = {`, ...
COMPONENT = re.compile(
    rb"ff_[A-Za-z0-9_]*(?:_decoder|_encoder|_demuxer|_muxer|_protocol|_bsf)\s*=\s*\{"
)
NAME = re.compile(rb'\.name\s*=\s*"([^"\\\n]{1,80})"')


def component_names(source: Path) -> set[str]:
    """Every component name literal the FFmpeg sources can register."""

    names: set[str] = set()
    for path in sorted((source / "libavcodec").glob("*.c")) + sorted(
        (source / "libavformat").glob("*.c")
    ) + sorted((source / "libavutil").glob("*.c")):
        data = path.read_bytes()
        if not COMPONENT.search(data):
            continue
        names.update(match.decode("utf-8") for match in NAME.findall(data))
    return names


def strings_of(data: bytes) -> set[bytes]:
    return set(STRING.findall(data))


def app_main(path: Path) -> bytes:
    """The app's main binary, from an IPA or from a loose Mach-O file."""

    if path.suffix.lower() != ".ipa":
        return path.read_bytes()
    with zipfile.ZipFile(path) as archive:
        plists = [n for n in archive.namelist() if re.fullmatch(r"Payload/[^/]+\.app/Info\.plist", n)]
        if len(plists) != 1:
            raise ValueError(f"{path} has {len(plists)} app bundles in Payload/")
        bundle = plists[0].rsplit("/", 1)[0]
        info = plistlib.loads(archive.read(plists[0]))
        return archive.read(f"{bundle}/{info['CFBundleExecutable']}")


def report(app: bytes, unit: bytes, names: set[str]) -> str:
    # Substring search, not extracted-string equality: the linker merges a
    # literal that is a suffix of another (`segment` into
    # `stream_segment,ssegment`), so equality would report a component missing
    # that is in fact there.
    def has(haystack: bytes, name: str) -> bool:
        return name.encode("utf-8") in haystack

    missing = sorted(n for n in names if has(app, n) and not has(unit, n))
    added = sorted(n for n in names if has(unit, n) and not has(app, n))

    lines = [
        "# ffmpeg-core enable-set comparison",
        "",
        "Component name literals from the FFmpeg sources (`ff_*_decoder`, `_encoder`,",
        "`_demuxer`, `_muxer`, `_protocol`, `_bsf`) that the app's main binary carries",
        "and the built `LibFFmpegCoreBridge.dylib` carries. Generated by",
        "`dev/tools/enable_set_diff.py`; a name here can also be a coincidental string",
        "in either binary, so the lists are short enough to read.",
        "",
        f"- candidates: {len(names)}",
        f"- present in the app: {sum(1 for n in names if has(app, n))}",
        f"- present in the unit: {sum(1 for n in names if has(unit, n))}",
        "",
        "## In the app, not in the unit (would stay on 4.4.5)",
        "",
    ]
    lines += [f"- `{n}`" for n in missing] or ["- (none)"]
    lines += ["", "## In the unit, not in the app (capability the unit adds)", ""]
    lines += [f"- `{n}`" for n in added] or ["- (none)"]
    lines += [
        "",
        "## Not covered by this comparison",
        "",
        "- parsers (no name literal; keyed by codec id),",
        "- hardware accelerators (name literals exist but the app uses none),",
        "- the exact `configure` options of the app's build, which are not recorded.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app", type=Path, default=ROOT.parent / "nPlayer_3.13.0.ipa")
    parser.add_argument("--unit", type=Path, default=ROOT / "build/LibFFmpegCoreBridge.dylib")
    parser.add_argument("--source", type=Path, default=ROOT / "build/ffmpeg-src/ffmpeg-4.4.5")
    args = parser.parse_args(argv)
    for path in (args.app, args.unit, args.source):
        if not path.exists():
            raise SystemExit(f"missing input: {path}")
    sys.stdout.write(report(app_main(args.app), args.unit.read_bytes(), component_names(args.source)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
